---
flock1:
  alignment:
    enabled: 1
    magnitude: 0.01
  box:
    dist: 25.0
    enabled: 1
    end: [400, 400, 400]
    speed: 5.0
    start: [-400, 40, -400]
  boxlimit:
    enabled: 1
    end: [400, 400, 400]
    start: [-400, 30, -400]
  cohersion:
    enabled: 1
    magnitude: 0.01
  flee:
    enabled: 1
    radius: 120.0
    scare: 20.0
  follow:
    magnitude: 0.08  # Never read
  goto:
    home:
      - 0  # Never read
      - 0  # Never read
      - 0  # Never read
    magnitude: 0.01  # Never read
    random: 100.0  # Never read
  multigoto:
    enabled: 0
    magnitude: 2.5
  random:
    enabled: 1
    magnitude: 8.0
  separation:
    dist: 18.0
    enabled: 1
  size: 200
  speed:
    enabled: 1
    max: 70.0
    min: 40.0
meta:
  display:
    fov:
      min: 0.0
      max: 3.14
      step: 0.01
  flock1:
    alignment:
      magnitude:
        max: 1.0
        min: 0.0
        step: 0.01
    follow:
      magnitude:
        max: 1.0
        min: 0.0
        step: 0.01

screen:
  width: 1280
  height: 800
  

laserSensor:
  offset: [0.0, -800.0, 0.0]
  epsilon: 0.10
  minPoints: 3

screenplay:
  secsBeforeSharkAnimationMin: 1.0
  secsBeforeSharkAnimationMax: 5.0
  secsBeforeSharkReset: 2.0
  secsBeforeWaterSplash: 35.0
  secsOfWaterSplash: 2.0
